version: 0.2

phases:
  install:
    commands:
      - echo "Iniciando pipeline..."

  build:
    commands:
      - echo "Validando archivos..."
      - ls pagina/

  post_build:
    commands:
      - echo "Subiendo pagina a S3..."
      - aws s3 cp pagina/ s3://devopsprueba1/pagina/ --recursive

artifacts:
  files:
    - pagina/pagina.html
    - pagina/style.css
  base-directory: .
